$axure.loadCurrentPage({
  "url":"学生列表.html",
  "generationDate":new Date(1528469265398.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0186122d72c54acfa2ee53a5c27f1cd8",
    "type":"Axure:Page",
    "name":"学生列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b78ecdc7d2974a5689b076e532835c50",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":90},
            "size":{
              "width":790,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3afc35b8125437ca767d7a0fb66540b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":90},
                "size":{
                  "width":790,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u0.png"}},
{
          "id":"955688282e6b457c8b82096bc1c6b62e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Bold', '仿宋'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CC33,
              "opacity":1},
            "location":{
              "x":280,
              "y":130},
            "size":{
              "width":210,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab0989447b294bd68537b699af5c1cbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Bold', '仿宋'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CC33,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":130},
                "size":{
                  "width":210,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a98b2c78979645119b6136e239373fab",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":140},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"bad1a7bb0aea4ee5a3db7264c1fcbf19",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":140},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面老师",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0a2ebbbb8cd54254871d7cedbdd65269",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":940,
              "y":390},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e443d8318be34f1bbe1d3fc2ec6e4a52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":940,
                  "y":390},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92bbda25502445e5a6a5688d76182132",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":290},
            "size":{
              "width":300,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48973e41905442ac9b7c7b8a4036e9ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cf624011db9249ccb956ad28109e972b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u9.png"}},
{
              "id":"33c6860e58714197862eee9e6fc6a09a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19607b119c764acfbfcc3ef5e0f31021",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u9.png"}},
{
              "id":"1bf1b982032949adb42c9921a94302d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85ea3cc6c588481fb34b00b8201ef847",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u21.png"}},
{
              "id":"d86c9d1937f344629fd3d5a54c4d983e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4277f7fecbc4a8bae4751b70ab54386",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u9.png"}},
{
              "id":"d3c1d814cea2469a9f1ab3cb6deea381",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bcb7d4f0c5c34ea582d8d9a55298cff6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u9.png"}},
{
              "id":"114e4e5bca9544e69a99ecffc74b742c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b8e1fd605907405ca95fe4774fd12910",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u21.png"}},
{
              "id":"57cad9e771ec442ca2d4a21ffb977425",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90d73d16bdb9483bbb255792487706b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u13.png"}},
{
              "id":"590244a0da8442ba89337b37d105e1a0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"320d7ec5a5804db2a154165fb200d08c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u13.png"}},
{
              "id":"42ceaacb6e854d70b84a93f6998e2ce7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18b259bc8f5248519daa278e89f045b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u25.png"}},
{
              "id":"1c0455f4b7fc41e4a0c8123999bf79dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb406ed9cccb411fbc0f6534c2c5eec6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u21.png"}},
{
              "id":"829bb227cb234b50935e701f0c537dc5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b0a7b6702ba460c9123d670df933f52",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":100},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u21.png"}},
{
              "id":"3bd1d8d0e1c44b749f1c05dd3b0d5d42",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":100},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b703fd2454543fc85eb82f7656fc6ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":100},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u25.png"}},
{
              "id":"75bff7da0e2c4e70987b736cf546c7e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2867614d3ea4c5d97146eba51a3be43",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u33.png"}},
{
              "id":"cd2197d078ed462aad466926376deb35",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":140},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c0561016a1884c0cbe8c896fbb13aa11",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u33.png"}},
{
              "id":"cfca821c8ce74e96af2a3ef5e5902ab6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":140},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3080797b05314a39a56ffbfdf44cf494",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生列表/u37.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "b78ecdc7d2974a5689b076e532835c50":{
      "scriptId":"u0"},
    "b3afc35b8125437ca767d7a0fb66540b":{
      "scriptId":"u1"},
    "955688282e6b457c8b82096bc1c6b62e":{
      "scriptId":"u2"},
    "ab0989447b294bd68537b699af5c1cbc":{
      "scriptId":"u3"},
    "a98b2c78979645119b6136e239373fab":{
      "scriptId":"u4"},
    "bad1a7bb0aea4ee5a3db7264c1fcbf19":{
      "scriptId":"u5"},
    "0a2ebbbb8cd54254871d7cedbdd65269":{
      "scriptId":"u6"},
    "e443d8318be34f1bbe1d3fc2ec6e4a52":{
      "scriptId":"u7"},
    "92bbda25502445e5a6a5688d76182132":{
      "scriptId":"u8"},
    "48973e41905442ac9b7c7b8a4036e9ee":{
      "scriptId":"u9"},
    "cf624011db9249ccb956ad28109e972b":{
      "scriptId":"u10"},
    "d86c9d1937f344629fd3d5a54c4d983e":{
      "scriptId":"u11"},
    "b4277f7fecbc4a8bae4751b70ab54386":{
      "scriptId":"u12"},
    "57cad9e771ec442ca2d4a21ffb977425":{
      "scriptId":"u13"},
    "90d73d16bdb9483bbb255792487706b1":{
      "scriptId":"u14"},
    "33c6860e58714197862eee9e6fc6a09a":{
      "scriptId":"u15"},
    "19607b119c764acfbfcc3ef5e0f31021":{
      "scriptId":"u16"},
    "d3c1d814cea2469a9f1ab3cb6deea381":{
      "scriptId":"u17"},
    "bcb7d4f0c5c34ea582d8d9a55298cff6":{
      "scriptId":"u18"},
    "590244a0da8442ba89337b37d105e1a0":{
      "scriptId":"u19"},
    "320d7ec5a5804db2a154165fb200d08c":{
      "scriptId":"u20"},
    "1bf1b982032949adb42c9921a94302d8":{
      "scriptId":"u21"},
    "85ea3cc6c588481fb34b00b8201ef847":{
      "scriptId":"u22"},
    "114e4e5bca9544e69a99ecffc74b742c":{
      "scriptId":"u23"},
    "b8e1fd605907405ca95fe4774fd12910":{
      "scriptId":"u24"},
    "42ceaacb6e854d70b84a93f6998e2ce7":{
      "scriptId":"u25"},
    "18b259bc8f5248519daa278e89f045b3":{
      "scriptId":"u26"},
    "1c0455f4b7fc41e4a0c8123999bf79dc":{
      "scriptId":"u27"},
    "fb406ed9cccb411fbc0f6534c2c5eec6":{
      "scriptId":"u28"},
    "829bb227cb234b50935e701f0c537dc5":{
      "scriptId":"u29"},
    "8b0a7b6702ba460c9123d670df933f52":{
      "scriptId":"u30"},
    "3bd1d8d0e1c44b749f1c05dd3b0d5d42":{
      "scriptId":"u31"},
    "8b703fd2454543fc85eb82f7656fc6ff":{
      "scriptId":"u32"},
    "75bff7da0e2c4e70987b736cf546c7e4":{
      "scriptId":"u33"},
    "a2867614d3ea4c5d97146eba51a3be43":{
      "scriptId":"u34"},
    "cd2197d078ed462aad466926376deb35":{
      "scriptId":"u35"},
    "c0561016a1884c0cbe8c896fbb13aa11":{
      "scriptId":"u36"},
    "cfca821c8ce74e96af2a3ef5e5902ab6":{
      "scriptId":"u37"},
    "3080797b05314a39a56ffbfdf44cf494":{
      "scriptId":"u38"}}});