$axure.loadCurrentPage({
  "url":"用户信息老师.html",
  "generationDate":new Date(1528469265940.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fff92dbe8eb044c3b576a2bb68bccee7",
    "type":"Axure:Page",
    "name":"用户信息老师",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ac408460e8764ae08ec455eefea21eff",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":90},
            "size":{
              "width":790,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4bc01a563934160858710e9ac33ace9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":90},
                "size":{
                  "width":790,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u0.png"}},
{
          "id":"de3c91d2fa414ed3ad13ce5bd0968535",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Bold', '仿宋'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CC33,
              "opacity":1},
            "location":{
              "x":280,
              "y":130},
            "size":{
              "width":210,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebbe8e5dc41a4e3ab7202b8b5985482a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Bold', '仿宋'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CC33,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":130},
                "size":{
                  "width":210,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5194c0d944c24bdb97334fdccfa4ef82",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":140},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"790fe9b92e424698916bbb2c4baf9f34",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":240},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deb5392a0b214bb79c75d705e5251c5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":240},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"8a001b01fffd46f9be41a2a65a2fda56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":240},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc65b6900d72401fb7c05d8a206ff9c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":240},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"f29d181578bc41c4ad97a4132b648df7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":280},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d48d4e2ea4442cbb936b5604d4c172f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":280},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"4e350dc857bd403ba57a282dfe87d468",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":320},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b0dc2810c5f4c29869298487c0df55a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":320},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"443b0074c58742e7ac14738e46cefa9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":280},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8676a86a5704585ad33890e48e198c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":280},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"88e93027a0284cebbbc015a522f3f390",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":320},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39255b1269e143e4932ae4ac283f6819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":320},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"70c72ae4f3654ac89e6387a59a6f91d4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":520},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"66558934f02f475d82e220cfb36c9ca1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":360},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"087d8c3c28914ee88a47f1df478ff9a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":360},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"0844dea1dddf44bf86107648b49f4141",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":400},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b566d22b2d4f8db6b077823dd6b894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":400},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"88c14a05c4764c8795d16c38eea01019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":360},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52b6d9b0c9be48f2a02d74c7b87e5494",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":360},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"ab7cde4a84c64b62a2805da30ee60549",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":400},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcee38a79a6b42869c3bc54f4aab32f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":400},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"ae7e70f3280048b9aeb53909a5d8922f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":140},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面老师",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3816e882d2eb40a8992aaf64b6c0e305",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":240},
            "size":{
              "width":100,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f732bd92a2c5484a915b26353d217965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":240},
                "size":{
                  "width":100,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息学生/u27.png"}},
{
          "id":"b4e5c768adfc423292faf0023d02652a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":945,
              "y":255},
            "size":{
              "width":50,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8143b14b41a44da2b5d8b444b29ebd58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":945,
                  "y":255},
                "size":{
                  "width":50,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息学生/u29.png"}},
{
          "id":"30873cc2615e4502bb2d2aa426bc74fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":940,
              "y":390},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a77495e201cd4c3083768af78b2bc9b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":940,
                  "y":390},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d28e1229e156439484d2fedb66137d03",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":385.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "ac408460e8764ae08ec455eefea21eff":{
      "scriptId":"u0"},
    "f4bc01a563934160858710e9ac33ace9":{
      "scriptId":"u1"},
    "de3c91d2fa414ed3ad13ce5bd0968535":{
      "scriptId":"u2"},
    "ebbe8e5dc41a4e3ab7202b8b5985482a":{
      "scriptId":"u3"},
    "5194c0d944c24bdb97334fdccfa4ef82":{
      "scriptId":"u4"},
    "790fe9b92e424698916bbb2c4baf9f34":{
      "scriptId":"u5"},
    "deb5392a0b214bb79c75d705e5251c5a":{
      "scriptId":"u6"},
    "8a001b01fffd46f9be41a2a65a2fda56":{
      "scriptId":"u7"},
    "cc65b6900d72401fb7c05d8a206ff9c2":{
      "scriptId":"u8"},
    "f29d181578bc41c4ad97a4132b648df7":{
      "scriptId":"u9"},
    "5d48d4e2ea4442cbb936b5604d4c172f":{
      "scriptId":"u10"},
    "4e350dc857bd403ba57a282dfe87d468":{
      "scriptId":"u11"},
    "2b0dc2810c5f4c29869298487c0df55a":{
      "scriptId":"u12"},
    "443b0074c58742e7ac14738e46cefa9f":{
      "scriptId":"u13"},
    "c8676a86a5704585ad33890e48e198c6":{
      "scriptId":"u14"},
    "88e93027a0284cebbbc015a522f3f390":{
      "scriptId":"u15"},
    "39255b1269e143e4932ae4ac283f6819":{
      "scriptId":"u16"},
    "70c72ae4f3654ac89e6387a59a6f91d4":{
      "scriptId":"u17"},
    "66558934f02f475d82e220cfb36c9ca1":{
      "scriptId":"u18"},
    "087d8c3c28914ee88a47f1df478ff9a4":{
      "scriptId":"u19"},
    "0844dea1dddf44bf86107648b49f4141":{
      "scriptId":"u20"},
    "b9b566d22b2d4f8db6b077823dd6b894":{
      "scriptId":"u21"},
    "88c14a05c4764c8795d16c38eea01019":{
      "scriptId":"u22"},
    "52b6d9b0c9be48f2a02d74c7b87e5494":{
      "scriptId":"u23"},
    "ab7cde4a84c64b62a2805da30ee60549":{
      "scriptId":"u24"},
    "fcee38a79a6b42869c3bc54f4aab32f5":{
      "scriptId":"u25"},
    "ae7e70f3280048b9aeb53909a5d8922f":{
      "scriptId":"u26"},
    "3816e882d2eb40a8992aaf64b6c0e305":{
      "scriptId":"u27"},
    "f732bd92a2c5484a915b26353d217965":{
      "scriptId":"u28"},
    "b4e5c768adfc423292faf0023d02652a":{
      "scriptId":"u29"},
    "8143b14b41a44da2b5d8b444b29ebd58":{
      "scriptId":"u30"},
    "30873cc2615e4502bb2d2aa426bc74fc":{
      "scriptId":"u31"},
    "a77495e201cd4c3083768af78b2bc9b1":{
      "scriptId":"u32"},
    "d28e1229e156439484d2fedb66137d03":{
      "scriptId":"u33"}}});