$axure.loadCurrentPage({
  "url":"修改密码.html",
  "generationDate":new Date(1528469265178.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"879f7db604b949848427b80282fe0fdb",
    "type":"Axure:Page",
    "name":"修改密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9c4b7b2a25bf498a923da21a51f37916",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":90},
            "size":{
              "width":790,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"303841f094a84e7aba6417208236cb7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":90},
                "size":{
                  "width":790,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u0.png"}},
{
          "id":"27c66a50957d403a8545248d4fd95ff9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Bold', '仿宋'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CC33,
              "opacity":1},
            "location":{
              "x":280,
              "y":130},
            "size":{
              "width":210,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83701e28975541c499f597ef5c01f096",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Bold', '仿宋'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CC33,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":130},
                "size":{
                  "width":210,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8a0f31bd62e4dab8a76ee159d903a4e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":320},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2add37c1454cc9b42a58d7e700d4e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":320},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"ce6c05a741764b7f80f37243442ff98b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":320},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb5f2f9663b547079236d75b82827af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":320},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"eabbf11492e14da9bf2d0a982e70d277",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":520},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"60e625be139f4554907d5a5d00716f57",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":360},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cea23a9bd78483b9a844d1a9d5ca48c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":360},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"52de601f353a41919698c15463f44c7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":360},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2297278817104a6aa8ab4be9ae8c09f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":360},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"cdd90cffc97e4cae93be029b23eaad5d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":140},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面老师",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"06bfc06e79a142d18a3dd06f398d8e69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":940,
              "y":390},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cece2ee8c194a8b88dc3de479e17220",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":940,
                  "y":390},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9c4b7b2a25bf498a923da21a51f37916":{
      "scriptId":"u0"},
    "303841f094a84e7aba6417208236cb7b":{
      "scriptId":"u1"},
    "27c66a50957d403a8545248d4fd95ff9":{
      "scriptId":"u2"},
    "83701e28975541c499f597ef5c01f096":{
      "scriptId":"u3"},
    "e8a0f31bd62e4dab8a76ee159d903a4e":{
      "scriptId":"u4"},
    "4e2add37c1454cc9b42a58d7e700d4e3":{
      "scriptId":"u5"},
    "ce6c05a741764b7f80f37243442ff98b":{
      "scriptId":"u6"},
    "bb5f2f9663b547079236d75b82827af4":{
      "scriptId":"u7"},
    "eabbf11492e14da9bf2d0a982e70d277":{
      "scriptId":"u8"},
    "60e625be139f4554907d5a5d00716f57":{
      "scriptId":"u9"},
    "0cea23a9bd78483b9a844d1a9d5ca48c":{
      "scriptId":"u10"},
    "52de601f353a41919698c15463f44c7e":{
      "scriptId":"u11"},
    "2297278817104a6aa8ab4be9ae8c09f8":{
      "scriptId":"u12"},
    "cdd90cffc97e4cae93be029b23eaad5d":{
      "scriptId":"u13"},
    "06bfc06e79a142d18a3dd06f398d8e69":{
      "scriptId":"u14"},
    "2cece2ee8c194a8b88dc3de479e17220":{
      "scriptId":"u15"}}});