$axure.loadCurrentPage({
  "url":"用户界面老师.html",
  "generationDate":new Date(1528469265291.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0dfa51ecc1a24c85823bcc4bfe90f707",
    "type":"Axure:Page",
    "name":"用户界面老师",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f98c751612f429fa8b54f0cc9a12989",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":90},
            "size":{
              "width":790,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f933ee336124d5f93e4872233413345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":90},
                "size":{
                  "width":790,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u0.png"}},
{
          "id":"c6fc6799f6934d64ad26b2a61b7d9a56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Bold', '仿宋'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CC33,
              "opacity":1},
            "location":{
              "x":280,
              "y":130},
            "size":{
              "width":210,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a57045244f84bb68707b0ee4475f4dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Bold', '仿宋'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CC33,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":130},
                "size":{
                  "width":210,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed683d9032a74a1da8a3e1e37fb5e52a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":140},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"77603b31f7514f68b57934c4055744ee",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":240},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5ec141d7b114dba9e7d2848097ba326",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":240},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"a7e2a2f4f2304fbdb492ba8e1446eae4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":149},
            "size":{
              "width":120,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a43e5d461c3c4cd2bf024f5dcc5ce700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":149},
                "size":{
                  "width":120,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"677a8cb004ac4058bce9ce41bfb05975",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":240},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3cdb6a6da7d4723844e7fb2b7d09113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":240},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"582f31b6f4294e8687a8cd4617a35ec9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":280},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a4551262ffa4f76b4840e8728a89398",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":280},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"cde1727c84664b8dbab45121ce59a019",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":320},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d1f30c8c17a4a4d9f4ca0f2a0bc2462",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":320},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"7400febc58004b4fa812f04ee586194c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":280},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"518655d86ba543f780b3ea58a3a32504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":280},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"2d873cd75a9144c5aff17838839032e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":320},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b58394c7d7c64b38b20abda05a49c1fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":320},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"96ffc2c0c0484685a3daafc684df92ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":384},
            "size":{
              "width":70,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31d92d716c4141a2bb93c29e06b7351b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":384},
                "size":{
                  "width":70,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c7366e1785c44749c5ee7e0965aa0e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":410},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02bfda6cc1734f318747c94d48577620",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":410},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评定成绩/u5.png"}},
{
          "id":"3e9fa53d9d7f4403b5fe18f29562c4bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":480},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a61e984d9524143a4cf8ce8d57f770a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":480},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评定成绩/u5.png"}},
{
          "id":"4fc7a2399dc4474c8f101d85bc272c6c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":140},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户信息老师",
                      "target":{
                        "targetType":"page",
                        "url":"用户信息老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a279154fe4764e728a18d00deb559363",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":520},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评定成绩",
                      "target":{
                        "targetType":"page",
                        "url":"评定成绩.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2aa28bfd7a9345edac26184c142c1416",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":520},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生列表",
                      "target":{
                        "targetType":"page",
                        "url":"学生列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "8f98c751612f429fa8b54f0cc9a12989":{
      "scriptId":"u0"},
    "5f933ee336124d5f93e4872233413345":{
      "scriptId":"u1"},
    "c6fc6799f6934d64ad26b2a61b7d9a56":{
      "scriptId":"u2"},
    "5a57045244f84bb68707b0ee4475f4dc":{
      "scriptId":"u3"},
    "ed683d9032a74a1da8a3e1e37fb5e52a":{
      "scriptId":"u4"},
    "77603b31f7514f68b57934c4055744ee":{
      "scriptId":"u5"},
    "f5ec141d7b114dba9e7d2848097ba326":{
      "scriptId":"u6"},
    "a7e2a2f4f2304fbdb492ba8e1446eae4":{
      "scriptId":"u7"},
    "a43e5d461c3c4cd2bf024f5dcc5ce700":{
      "scriptId":"u8"},
    "677a8cb004ac4058bce9ce41bfb05975":{
      "scriptId":"u9"},
    "e3cdb6a6da7d4723844e7fb2b7d09113":{
      "scriptId":"u10"},
    "582f31b6f4294e8687a8cd4617a35ec9":{
      "scriptId":"u11"},
    "9a4551262ffa4f76b4840e8728a89398":{
      "scriptId":"u12"},
    "cde1727c84664b8dbab45121ce59a019":{
      "scriptId":"u13"},
    "5d1f30c8c17a4a4d9f4ca0f2a0bc2462":{
      "scriptId":"u14"},
    "7400febc58004b4fa812f04ee586194c":{
      "scriptId":"u15"},
    "518655d86ba543f780b3ea58a3a32504":{
      "scriptId":"u16"},
    "2d873cd75a9144c5aff17838839032e6":{
      "scriptId":"u17"},
    "b58394c7d7c64b38b20abda05a49c1fe":{
      "scriptId":"u18"},
    "96ffc2c0c0484685a3daafc684df92ed":{
      "scriptId":"u19"},
    "31d92d716c4141a2bb93c29e06b7351b":{
      "scriptId":"u20"},
    "2c7366e1785c44749c5ee7e0965aa0e3":{
      "scriptId":"u21"},
    "02bfda6cc1734f318747c94d48577620":{
      "scriptId":"u22"},
    "3e9fa53d9d7f4403b5fe18f29562c4bd":{
      "scriptId":"u23"},
    "1a61e984d9524143a4cf8ce8d57f770a":{
      "scriptId":"u24"},
    "4fc7a2399dc4474c8f101d85bc272c6c":{
      "scriptId":"u25"},
    "a279154fe4764e728a18d00deb559363":{
      "scriptId":"u26"},
    "2aa28bfd7a9345edac26184c142c1416":{
      "scriptId":"u27"}}});