$axure.loadCurrentPage({
  "url":"用户信息学生.html",
  "generationDate":new Date(1528469265736.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"889af26437714f33a6e4e1204600be47",
    "type":"Axure:Page",
    "name":"用户信息学生",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d1476d388e7841a4879b1179b65c8528",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":90},
            "size":{
              "width":790,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e94d03ba4d2f4dadb76b13588f5403ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":90},
                "size":{
                  "width":790,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u0.png"}},
{
          "id":"27a5c56cf5604e9598cd6977f1f368ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Bold', '仿宋'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CC33,
              "opacity":1},
            "location":{
              "x":280,
              "y":130},
            "size":{
              "width":210,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"880dde9417684b5190f214b4f7e1f5f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Bold', '仿宋'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CC33,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":130},
                "size":{
                  "width":210,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41aa8bfa0b4548a0bf948191f2756a82",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":140},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d93c99863aae48bf80a2929beea42d93",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":240},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2d55d2f6d30441884aa8bbe29840142",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":240},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"71c3b276f4a3491899a23281b19b5e89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":240},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e7fbf061d3b44e6b20704524989f317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":240},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"a40365a9beef48e6b7169304d6c6dd20",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":280},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"901375550ee54825958566bbb37d833c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":280},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"ecdb5cd7b87b4271b12e9f4c1401c8e0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":320},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0dbb41ce7a04940988707ed38edf1b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":320},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"ffde691ce3bc4b8cb9e0a32e2e93ada7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":280},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a216632c6f14c94bb763a41986800e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":280},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"3261921f9862452ca7998549799981ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":320},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c58085516db84e3592076abbf2fba2de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":320},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"058f3bb353e84ee19215606bb71390bf",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":520},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"eaec693329474a8bb25151baa4f67970",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":360},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d367950a4f44e56ac547f90713b2736",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":360},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"429e87853a5e4466a2873e8cdb9a5623",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":400},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25243319114a412ba4863d9a65725db3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":400},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u4.png"}},
{
          "id":"3f4dd1951c7843c2a8008375662f500d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":360},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d90b631773c4458810057a1eb14cddb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":360},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"62be4c4b357e464b93f8ca4d7a69bdc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":400},
            "size":{
              "width":170,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49de7483b556465698446a49056c83db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":400},
                "size":{
                  "width":170,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u6.png"}},
{
          "id":"13a8207a225a4d2d91dc8c90283daad7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":140},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面学生",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面学生.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9d398ae3da86403ea32221f7936e0774",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":240},
            "size":{
              "width":100,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d421418dc1594f62a40b17db82461e42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":240},
                "size":{
                  "width":100,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息学生/u27.png"}},
{
          "id":"5f4883b376ca42e69bd66d4a7ded25b2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":945,
              "y":255},
            "size":{
              "width":50,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"941b4df93f3d413abc8bb2c96735abd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":945,
                  "y":255},
                "size":{
                  "width":50,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息学生/u29.png"}},
{
          "id":"59d8b2027e5f48c5b0452657167be7cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":940,
              "y":390},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50ad49e021214979bc5c5a36d5f96e13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":940,
                  "y":390},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9e244bd69be4f1e8335be16f53cc240",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":385.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "d1476d388e7841a4879b1179b65c8528":{
      "scriptId":"u0"},
    "e94d03ba4d2f4dadb76b13588f5403ab":{
      "scriptId":"u1"},
    "27a5c56cf5604e9598cd6977f1f368ab":{
      "scriptId":"u2"},
    "880dde9417684b5190f214b4f7e1f5f9":{
      "scriptId":"u3"},
    "41aa8bfa0b4548a0bf948191f2756a82":{
      "scriptId":"u4"},
    "d93c99863aae48bf80a2929beea42d93":{
      "scriptId":"u5"},
    "b2d55d2f6d30441884aa8bbe29840142":{
      "scriptId":"u6"},
    "71c3b276f4a3491899a23281b19b5e89":{
      "scriptId":"u7"},
    "5e7fbf061d3b44e6b20704524989f317":{
      "scriptId":"u8"},
    "a40365a9beef48e6b7169304d6c6dd20":{
      "scriptId":"u9"},
    "901375550ee54825958566bbb37d833c":{
      "scriptId":"u10"},
    "ecdb5cd7b87b4271b12e9f4c1401c8e0":{
      "scriptId":"u11"},
    "d0dbb41ce7a04940988707ed38edf1b1":{
      "scriptId":"u12"},
    "ffde691ce3bc4b8cb9e0a32e2e93ada7":{
      "scriptId":"u13"},
    "2a216632c6f14c94bb763a41986800e2":{
      "scriptId":"u14"},
    "3261921f9862452ca7998549799981ac":{
      "scriptId":"u15"},
    "c58085516db84e3592076abbf2fba2de":{
      "scriptId":"u16"},
    "058f3bb353e84ee19215606bb71390bf":{
      "scriptId":"u17"},
    "eaec693329474a8bb25151baa4f67970":{
      "scriptId":"u18"},
    "5d367950a4f44e56ac547f90713b2736":{
      "scriptId":"u19"},
    "429e87853a5e4466a2873e8cdb9a5623":{
      "scriptId":"u20"},
    "25243319114a412ba4863d9a65725db3":{
      "scriptId":"u21"},
    "3f4dd1951c7843c2a8008375662f500d":{
      "scriptId":"u22"},
    "1d90b631773c4458810057a1eb14cddb":{
      "scriptId":"u23"},
    "62be4c4b357e464b93f8ca4d7a69bdc1":{
      "scriptId":"u24"},
    "49de7483b556465698446a49056c83db":{
      "scriptId":"u25"},
    "13a8207a225a4d2d91dc8c90283daad7":{
      "scriptId":"u26"},
    "9d398ae3da86403ea32221f7936e0774":{
      "scriptId":"u27"},
    "d421418dc1594f62a40b17db82461e42":{
      "scriptId":"u28"},
    "5f4883b376ca42e69bd66d4a7ded25b2":{
      "scriptId":"u29"},
    "941b4df93f3d413abc8bb2c96735abd3":{
      "scriptId":"u30"},
    "59d8b2027e5f48c5b0452657167be7cc":{
      "scriptId":"u31"},
    "50ad49e021214979bc5c5a36d5f96e13":{
      "scriptId":"u32"},
    "d9e244bd69be4f1e8335be16f53cc240":{
      "scriptId":"u33"}}});