$axure.loadCurrentPage({
  "url":"查看成绩.html",
  "generationDate":new Date(1528469265631.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e1fa88a6eab545a0a56e8419c2e1ce1d",
    "type":"Axure:Page",
    "name":"查看成绩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"99cca0366f6f457282074e90cab454bf",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":70},
            "size":{
              "width":790,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93f0c1b71c31492aa43b60a433dea944",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":70},
                "size":{
                  "width":790,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u0.png"}},
{
          "id":"5a3234a6e3da421c9ebea6000524550a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Bold', '仿宋'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CC33,
              "opacity":1},
            "location":{
              "x":180,
              "y":110},
            "size":{
              "width":210,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e9b207ef17845b09b99105e4541e647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Bold', '仿宋'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CC33,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":110},
                "size":{
                  "width":210,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58a368da79d5489aaf72582f9d431091",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":120},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面学生",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面学生.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"21140d59751b454189d610fa351d240e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":214},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b59e870648e8443e99da3f471549a88f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":214},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9ef9668ff8d48d39681867fe82f581e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":226},
            "size":{
              "width":230,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9128c4855efb4a1d926ce3412f21b86e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":226},
                "size":{
                  "width":230,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c89cac7a3bed45b58da2ec62d5b3f0d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":226},
            "size":{
              "width":230,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed9f8caf34bb4e6da342313812864a59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":226},
                "size":{
                  "width":230,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3408dd91a86d44548c0688e9102013e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":250,
              "y":381},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aaef63fc6e244948f4f86b228f09fac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":250,
                  "y":381},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b49656588cd43079107994368b6dd98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":410},
            "size":{
              "width":230,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3173ffbdea7a48ca8c0ab8b06856d459",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":410},
                "size":{
                  "width":230,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"473560ce224545f089bcddd909d66674",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":420},
            "size":{
              "width":230,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10416c0ec26946238c717cecf5074b95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":420},
                "size":{
                  "width":230,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "99cca0366f6f457282074e90cab454bf":{
      "scriptId":"u0"},
    "93f0c1b71c31492aa43b60a433dea944":{
      "scriptId":"u1"},
    "5a3234a6e3da421c9ebea6000524550a":{
      "scriptId":"u2"},
    "6e9b207ef17845b09b99105e4541e647":{
      "scriptId":"u3"},
    "58a368da79d5489aaf72582f9d431091":{
      "scriptId":"u4"},
    "21140d59751b454189d610fa351d240e":{
      "scriptId":"u5"},
    "b59e870648e8443e99da3f471549a88f":{
      "scriptId":"u6"},
    "b9ef9668ff8d48d39681867fe82f581e":{
      "scriptId":"u7"},
    "9128c4855efb4a1d926ce3412f21b86e":{
      "scriptId":"u8"},
    "c89cac7a3bed45b58da2ec62d5b3f0d4":{
      "scriptId":"u9"},
    "ed9f8caf34bb4e6da342313812864a59":{
      "scriptId":"u10"},
    "3408dd91a86d44548c0688e9102013e0":{
      "scriptId":"u11"},
    "9aaef63fc6e244948f4f86b228f09fac":{
      "scriptId":"u12"},
    "6b49656588cd43079107994368b6dd98":{
      "scriptId":"u13"},
    "3173ffbdea7a48ca8c0ab8b06856d459":{
      "scriptId":"u14"},
    "473560ce224545f089bcddd909d66674":{
      "scriptId":"u15"},
    "10416c0ec26946238c717cecf5074b95":{
      "scriptId":"u16"}}});