$axure.loadCurrentPage({
  "url":"评定成绩.html",
  "generationDate":new Date(1528469265230.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8402a8f8d98b458eb3209c2710468028",
    "type":"Axure:Page",
    "name":"评定成绩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"93226e6eff3e4cc7b8ea0eb63a110dfd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":90},
            "size":{
              "width":790,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d64d4d47f3a447eeb02093a1f04daa09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":90},
                "size":{
                  "width":790,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u0.png"}},
{
          "id":"3e1f0cc6b6294559aeb9379181e68932",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Bold', '仿宋'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CC33,
              "opacity":1},
            "location":{
              "x":280,
              "y":130},
            "size":{
              "width":210,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC6633}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44b2f864bf964152a6ebcf312a336a7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Bold', '仿宋'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CC33,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":130},
                "size":{
                  "width":210,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC6633}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9708ec990a524298a0570f8cba1b47d8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":140},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面老师",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"cf01817b5be34c028e449bdc75510a8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":140},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef542c75c7ab4d938ac327e16eff1002",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":140},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评定成绩/u5.png"}},
{
          "id":"1e01406107ad45b49cc06feff7757e92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":320},
            "size":{
              "width":230,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2031a9350fe5476788ada557d4674acb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":320},
                "size":{
                  "width":230,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"badc375c7ae344fcb0b48b1aca71eed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":330,
              "y":264},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2ec7342fae3414faf2e243d6c365525",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":330,
                  "y":264},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ee44143333d4d258091a71bc8eb401a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":320},
            "size":{
              "width":230,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27cb5e69c8b849ce836e9cfb311f50fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":320},
                "size":{
                  "width":230,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d236f6c88e98417d8f621cc7285a5045",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":350},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b46ab0644c7b4610a2519440c0212fa4",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":400},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"02e3c626f87b4e2989f90dc5aecb1ed6",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":400},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"b1aeec01ef624de790ac9a972a1e3cbe",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":350},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a910d6902a4443fb82bd9198e2b51ba0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":545},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "93226e6eff3e4cc7b8ea0eb63a110dfd":{
      "scriptId":"u0"},
    "d64d4d47f3a447eeb02093a1f04daa09":{
      "scriptId":"u1"},
    "3e1f0cc6b6294559aeb9379181e68932":{
      "scriptId":"u2"},
    "44b2f864bf964152a6ebcf312a336a7c":{
      "scriptId":"u3"},
    "9708ec990a524298a0570f8cba1b47d8":{
      "scriptId":"u4"},
    "cf01817b5be34c028e449bdc75510a8c":{
      "scriptId":"u5"},
    "ef542c75c7ab4d938ac327e16eff1002":{
      "scriptId":"u6"},
    "1e01406107ad45b49cc06feff7757e92":{
      "scriptId":"u7"},
    "2031a9350fe5476788ada557d4674acb":{
      "scriptId":"u8"},
    "badc375c7ae344fcb0b48b1aca71eed8":{
      "scriptId":"u9"},
    "d2ec7342fae3414faf2e243d6c365525":{
      "scriptId":"u10"},
    "4ee44143333d4d258091a71bc8eb401a":{
      "scriptId":"u11"},
    "27cb5e69c8b849ce836e9cfb311f50fe":{
      "scriptId":"u12"},
    "d236f6c88e98417d8f621cc7285a5045":{
      "scriptId":"u13"},
    "b46ab0644c7b4610a2519440c0212fa4":{
      "scriptId":"u14"},
    "02e3c626f87b4e2989f90dc5aecb1ed6":{
      "scriptId":"u15"},
    "b1aeec01ef624de790ac9a972a1e3cbe":{
      "scriptId":"u16"},
    "a910d6902a4443fb82bd9198e2b51ba0":{
      "scriptId":"u17"}}});